[tool.black]
line-length = 120               # Maximum line length

[tool.isort]
force_grid_wrap = 2             # Disable automatic row wrapping
include_trailing_comma = true   # Add a comma after the last element in parentheses
line_length = 120               # Maximum line length (recommended for Black compatibility)
lines_after_imports = 2         # Number of blank lines to leave after imports
multi_line_output = 3           # Use import format with hyphens in parentheses

[tool.mypy]
ignore_missing_imports = true   # Ignore missing type annotations for external libraries
strict = true                   # Enable strict mode for type checking
mypy_path = "src"               # Enable to use mypy from the `src` directory
explicit_package_bases = true   # Enable to prevent mypy from confusing local packages with installed packages
